---

name: flake8

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install project
      run: |
        pip install .
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Run flake8
      run: |
        pip install flake8
        flake8 --max-line-length=120 --format='::warning file=%(path)s,line=%(row)d::%(code)s %(text)s' .
