---

name: mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install project
      run: |
        pip install .
    - name: Run mypy
      run: |
        pip install mypy
        mypy --disallow-untyped-defs --ignore-missing-imports -p wgskex
